CREATE DATABASE FINAL

CREATE TABLE FINAL_CASTELLANOS (
    USU_ID SERIAL NOT NULL,
    USU_USUARIO VARCHAR (25);
    USU_NOMBRE VARCHAR (25);
    USU_PASI VARCHAR (25);
    USU_NOMBREUSUARIO VARCHAR (25);
    USU_TELEFONO INTEGER;
    USU_CORREO VARCHAR (25);
    USU_SITUACION SMALINT DEFAULT 1,
);